print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****")

#print("    *\n   * *\n  *   *\n *     *\n***   ***\n  *   *\n  *   *\n  *****")

#print("        *")
#print("       * *")
#print("      *   *")
#print("     *     *")
#print("    *       *")
#print("   *         *")
#print("  *           *")
#print(" *             *")
#print("*****       *****")
#print("  *           *")
#print("  *           *")
#print("  *           *")
#print("   ***********")

#print("    *" * 2)
#print("   * *" * 2)
#print("  *   *" * 2)
#print(" *     *" * 2)
#print("***   ***" * 2)
#print("  *   *" * 2)
#print("  *   *" * 2)
#print("  *****" * 2)

#print("    *")
#print("   * *")
#print("  *   *")
#print(" *     *")
#print("***   ***"
#print("  *   *")
#print("  *   *")
#print("  *****")

#Print("    *")
#print("   * *")
#print("  *   *")
#print(" *     *")
#print("***   ***")
#print("  *   *")
#print("  *   *")
#print("  *****")

#print("    *')
#print("   * *")
#print("  *   *")
#print(" *     *")
#print("***   ***")
#print("  *   *")
#print("  *   *")
#print("  *****")
